{% set name = "pyribs" %}
{% set pypi_name = "ribs" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/ribs-{{ version }}.tar.gz
  sha256: e6f2767db9eefab1be5534c2e8f50d699568c725428b8995d454c62b7c70c356

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pyribs-base =={{ version }}
    # Remaining deps come from the ribs[all] extra.
    - matplotlib-base >=3.0.0

test:
  imports:
    - ribs
    - ribs.visualize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/icaros-usc/pyribs
  summary: A bare-bones Python library for quality diversity optimization.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - btjanaka
